### ISSUE TITLE
When release the code?

### ISSUE THREAD

**Issue by sybapp** [rain305f/TIDA#1]
Hi, the TIDA is a really nice work, providing a new and interesting perspective of OSSL. When you can release your code? That would be very help for us.

**Comment by rain305f** [comment]
Thanks for your acknowledgement, we will release our code in two week later.

**Comment by MinaGhadimiAtigh** [comment]
Hi, thanks for the great work. I was wondering is there are any updates on the release of the code.

**Comment by rain305f** [comment]
We have released the code
